name: validation
run-name: validation - ${{github.workflow}}

on:
  push:
    branches:
      - main
      - master
  pull_request:
  workflow_call:
    outputs:
      in_progress_check:
        value: ${{ jobs.validation.outputs.in_progress_check }}
      branch_check:
        value: ${{ jobs.validation.outputs.branch_check }}
jobs:
  validation:
    runs-on: ubuntu-latest
    outputs:
      in_progress_check: ${{ steps.validation.outputs.in_progress_check }}
      branch_check: ${{ steps.validation.outputs.branch_check }}
    steps:
      - uses: actions/checkout@v3
      - name: in_progress_check
        id: in_progress
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          in_progress_check=$(gh run list --workflow ${{github.workflow}} --json status -q '.[].status' | grep in_progress | wc -l)
          echo "in_progress_check=${in_progress_check}" >> $GITHUB_OUTPUT
          echo $in_progress_check
      - name: branch_check
        id: branch
        if: ${{github.workflow}} == "운영 배포"
        run: |
          if [[ '${{ github.ref}}' != 'refs/heads/main' ]]; then
            echo "운영 배포는 마스터만 가능합니다."
            exit 1
          fi
      - name: force_start
        id: validation
        if: ${{ inputs.force_start}} == true
        run: |
          if [[ '${{ inputs.force_start}}' == true ]]; then
            echo ""
          fi

          

      - name: Determine deploy target
        id: determine
        shell: bash
        run: |
          if ${{ github.event_name == 'push' }}; then
            echo "target=prod" >> $GITHUB_OUTPUT
          else
            echo "target=${{ inputs.target }}" >> $GITHUB_OUTPUT
          fi
      - name: Validate target and branch
        run: |
          if [[ '${{ steps.determine.outputs.target }}' == 'prod' && ${{ github.ref }} != 'refs/heads/master' ]]; then
            echo "github.ref: ${{ github.ref }}, steps.determine.outputs.target: ${{ steps.determine.outputs.target }}"
            echo "Production 환경(prod target)은 master branch 만 배포가 가능합니다."
            exit 1
          fi
