name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: string
      ALL:
        type: string
    outputs:
      matrix:
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.make.outputs.matrix1 }}
    steps:
      - uses: actions/checkout@v3

      - name: check_inputs
        id: make
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: | 
          echo "----- env"
          echo "$INPUTS"
          echo "$INPUTS" >> inputs.json

          # 성공 케이스
          echo "----- 성공 케이스"
          echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"
          echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}" >> "$GITHUB_OUTPUT"

          # test1
          echo "----- 변수로 넣었음"
          echo "matrix_origin1={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"
          echo $matrix_origin1
          echo "matrix1=$matrix_origin1" >> "$GITHUB_OUTPUT"
          echo $matrix1

          # test2
          echo "----- \를 지웠음"
          echo "matrix_origin2={"include":[{"module":"api"},{"module":"batch"}]}"
          echo $matrix_origin2
          echo "matrix2=$matrix_origin2" >> "$GITHUB_OUTPUT"
          echo $matrix2

          echo "----- 그냥env 생성"
          echo "dummy1=aaaa" >> "$GITHUB_OUTPUT"

          echo "----- env 확인"
          env
          echo "----- export 확인"
          export

      - name: check
        id: check
        run: |

          echo "----- 그냥env 확인"
          echo ${{steps.make.outputs.dummy1}}
          echo $dummy1

          echo "----- matrix data 확인"
          echo ${{steps.make.outputs.matrix}}
          echo $matrix
          echo ${{steps.make.outputs.matrix1}}
          echo $matrix1
          echo ${{steps.make.outputs.matrix2}}
          echo $matrix2

          echo "----- env 확인"
          env
          echo "----- export 확인"
          export
