name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: string
      ALL:
        type: string
    outputs:
      matrix:
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.matrix1 }}
    steps:
      - uses: actions/checkout@v3

      - name: check_inputs
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: | 
          echo "----- env"
          echo "$INPUTS"
          echo "$INPUTS" >> inputs.json

          # test1
          echo "----- 변수로 넣었음"
          echo "matrix_origin1={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"
          matrix_origin1={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}
          echo $matrix_origin1
          echo "matrix1=$matrix_origin1" >> $GITHUB_ENV
          matrix1=$matrix_origin1
          echo $matrix1

          echo "----- env 확인"
          env
          echo "----- export 확인"
          export

      - name: check
        run: |
          echo "----- matrix data 확인"

          echo ${{env.matrix1}}
          echo $matrix1

          echo "----- env 확인"
          env
          echo "----- export 확인"
          export
