name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: string
      ALL:
        type: string
    outputs:
      matrix:
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.matrix }}
    steps:
      - uses: actions/checkout@v3

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"

      - name: check_inputs
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: | 
          # echo "-----env"
          # echo "$INPUTS"
          # # echo "-----JsonString"
          # echo -ne ${{ inputs.ALL.all }} | jq keys
          # echo -ne ${{ inputs.ALL.svc1 }} | jq keys
          # # echo "-----Json"
          # # echo ${{ fromJSON(inputs.ALL) }}

          echo "-----"
          # echo 'module_list=["svc1","svc2","svc3"]' >> $GITHUB_ENV
 
          echo "matrix={\"include\":[{\"module\":\"svc1\"},{\"module\":\"svc2\"},{\"module\":\"svc3\"}]}" >> $GITHUB_ENV

        # - id: set-matrix
        # run: |
        #   if [ ${{ MODULE_ALL}} == "true" ]; then
            
      # - name: see_result
      #   run: |
      #     echo ${{ env.matrix }}
      #     echo ${{ fromJSON(env.matrix) }}
