name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: string
      ALL:
        type: string
    outputs:
      matrix:
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.matrix }}
    steps:
      - uses: actions/checkout@v3

      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"

      - name: check_inputs
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: | 
          echo "-----env"
          echo "$INPUTS" >> inputs.json
          echo "-----get keys"
          filtered_modules=$(cat inputs.json | jq -rc 'to_entries | map(select(.value == true)) | map({module: .key})')
          matrix="{\"include\":$filtered_modules}"
          matrix_with_sed=$(echo "$matrix" | sed 's/"/\\\"/g')
          echo "-----"
          echo $matrix_with_sed
          echo '{\"include\":[{\"module\":\"svc1\"},{\"module\":\"svc2\"}]}'
          # echo "matrix=$matrix_with_sed" >> $GITHUB_ENV

          echo "-----"
          # echo 'module_list=["svc1","svc2","svc3"]' >> $GITHUB_ENV
 
          echo "matrix={\"include\":[{\"module\":\"svc1\"},{\"module\":\"svc2\"}]}" >> $GITHUB_ENV
          # echo "matrix={\"include\":[{\"project\":\"foo\"},{\"project\":\"bar\"}]}" >> $GITHUB_ENV

        # - id: set-matrix
        # run: |
        #   if [ ${{ MODULE_ALL }} == "true" ]; then
        #     all > true
        #   else 
            
      # - name: see_result
      #   run: |
      #     echo ${{ env.matrix }}
      #     echo ${{ fromJSON(env.matrix) }}
