name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: boolean
      MODULE_1:
        type: boolean
      MODULE_2:
        type: boolean
      MODULE_3:
        type: boolean

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
        module_list: ${{ env.module_list }}
    steps:
      - uses: actions/checkout@v3

    #   - name: Dump GitHub context
    #     env:
    #       GITHUB_CONTEXT: ${{ toJson(github) }}
    #     run: |
    #       echo "$GITHUB_CONTEXT"

      - name: check_inputs
        run: | 
          echo ${{ inputs.all }}
          echo ${{ inputs.svc1 }}
          echo ${{ inputs.svc2 }}
          echo ${{ inputs.svc3 }}
          echo "-----"
          echo ${{ fromJSON(inputs.all) }}
          echo ${{ fromJSON(inputs.svc1) }}
          echo ${{ fromJSON(inputs.svc2) }}
          echo ${{ fromJSON(inputs.svc3) }}
        #   echo "module_list=[${{ inputs.svc1 }}, ${in_progress_check}" >> $GITHUB_ENV
