name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: boolean
      MODULE_1:
        type: boolean
      MODULE_2:
        type: boolean
      MODULE_3:
        type: boolean
    outputs:
      module_list:
        value: ${{ jobs.setup.outputs.module_list }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
        module_list: ${{ env.module_list }}
    steps:
      - uses: actions/checkout@v3

    #   - name: Dump GitHub context
    #     env:
    #       GITHUB_CONTEXT: ${{ toJson(github) }}
    #     run: |
    #       echo "$GITHUB_CONTEXT"

      - name: check_inputs
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: | 
          echo "$INPUTS"
          echo ${{ inputs.all }}
          echo ${{ inputs.svc1 }}
          echo ${{ inputs.svc2 }}
          echo ${{ inputs.svc3 }}
          echo "-----"
          echo 'module_list=["svc1","svc2","svc3"]' >> $GITHUB_ENV
