name: Matrixsetup workflow

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      PROJECT_NAME:
        type: string
      MODULE_ALL:
        type: string
      ALL:
        type: string
    outputs:
      matrix:
        value: ${{ jobs.setup.outputs.matrix }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ env.matrix }}
    steps:
      - uses: actions/checkout@v3

      # - name: check_inputs
      #   env:
      #     INPUTS: ${{ toJSON(inputs) }}
      #   run: | 
      #     echo "-----env"
      #     echo "$INPUTS" >> inputs.json
      #     echo "-----get checked"
      #     filtered_modules=$(cat inputs.json | jq -rc 'to_entries | map(select(.value == true)) | map({module: .key})')
      #     matrix="{\"include\":$filtered_modules}"
      #     matrix_with_sed=$(echo "$matrix" | sed 's/"/\\\"/g')
      #     echo $matrix

      #     echo "-----values"
      #     echo "echo \$matrix_with_sed"
      #     echo $matrix_with_sed
      #     echo "echo '{\"include\":[{\"module\":\"API\"},{\"module\":\"BATCH\"}]}'"
      #     echo '{\"include\":[{\"module\":\"API\"},{\"module\":\"BATCH\"}]}'
      #     echo "matrix=$matrix_with_sed" >> $GITHUB_ENV

      #     echo "-----k-v"
      #     echo "echo "matrix=\$matrix_with_sed""
      #     echo "matrix=$matrix_with_sed"
      #     echo 'echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"'
      #     echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"
 
      #     # echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}" >> $GITHUB_ENV
      #     # echo "matrix={\"include\":[{\"project\":\"foo\"},{\"project\":\"bar\"}]}" >> $GITHUB_ENV

      - name: check_inputs
        env:
          INPUTS: ${{ toJSON(inputs) }}
        run: | 
          echo "----- env"
          echo "$INPUTS"
          echo "$INPUTS" >> inputs.json

          # 성공 케이스
          echo "----- 성공 케이스"
          echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"
          # echo "matrix={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}" >> $GITHUB_ENV

          # test1
          echo "----- 변수로 넣었음"
          echo "matrix_origin1={\"include\":[{\"module\":\"api\"},{\"module\":\"batch\"}]}"
          echo $matrix_origin1
          # echo "matrix=$matrix_origin1" >> $GITHUB_ENV
          echo $matrix1

          # test2
          echo "----- \를 지웠음"
          echo "matrix_origin2={"include":[{"module":"api"},{"module":"batch"}]}"
          echo $matrix_origin2
          echo "matrix=$matrix_origin2" >> $GITHUB_ENV
          echo $matrix2

          echo "----- env 확인"
          env
          echo "----- export 확인"
          export

      - name: check
        run: |
          echo "----- env 확인"
          env
          echo "----- export 확인"
          export
