name: Reusable Workflow
run-name: aaa

concurrency:
  group: "aaaa"
  cancel-in-progress: false

on:
  workflow_call:
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: sleep 30
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: |
      #     echo "$GITHUB_CONTEXT"

      - name: Get Short SHA
        run: |
          echo ${GITHUB_SHA}
          echo ${{github.sha}}
          echo "sha_short=${GITHUB_SHA::5}" >> $GITHUB_ENV
          echo "SHORT_SHA=`echo ${{github.sha}} | cut -c1-7`" >> $GITHUB_ENV
        
      - name: Post to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'C05J50BRRB3'  # Replace with your Slack channel ID or name
          payload: |
            {
              "text": "date",
              "attachments": [
                {
                  "color": "${{ env.color }}",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "aaa"
                      }
                    }
                  ]
                }
              ]
            }