name: prtest

on:
  workflow_call:
      
        
jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: env
      - name: Dump GitHub context1
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{env.GITHUB_ACTOR}}
      - name: Dump GitHub context2
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_ACTOR: "aaaa"
        run: |
          echo "$GITHUB_CONTEXT"
          echo ${{env.GITHUB_ACTOR}}
      - name: Dump GitHub context3
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Post to Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel-id: 'C05J50BRRB3'  # Replace with your Slack channel ID or name
          payload: |
            {
              "text": "prtest running",
              "attachments": [
                {
                  "color": "#36a64f",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": " ${{ github.event.pull_request.title }}, ${{ github.ref_name }} "
                      }
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "github.base_ref: ${{github.base_ref}} \n github.head_ref: ${{github.head_ref}} \n github.ref: ${{github.ref}}"
                      }
                    }
                  ]
                }
              ]
            }