name: validation
run-name: validation - ${{github.workflow}}

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:
    outputs:
      in_progress_check:
        value: ${{ jobs.validation.outputs.in_progress_check }}
jobs:
  validation:
    runs-on: ubuntu-latest
    # outputs:
    #   in_progress_check: ${{ jobs.validation.outputs.in_progress_check }}
    steps:
      - name: validation
        run: |
          in_progress_check=$(gh run list --workflow ${{github.workflow}} --json status -q '.[].status' | grep in_progress | wc -l)
          echo "in_progress_check=${in_progress_check}" >> $GITHUB_OUTPUT